# Use the official Node.js image as the base image
FROM node:18

# Set the working directory
WORKDIR /app/backend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Install PM2 globally
RUN npm install -g pm2

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Expose the port the app runs on
EXPOSE ${NEXT_JS_PORT}

# Start the application using PM2
CMD ["pm2-runtime", "start", "npm", "--", "start"]