# Use the official Node.js image as the base image
FROM node:latest

# Set the working directory
WORKDIR /app/apps/frontend-app

# Copy package.json and package-lock.json
COPY package*.json ./

# Set environment to production
ENV NODE_ENV=production

# Copy the rest of the application code
COPY ./apps/frontend-app .

# Build the application
RUN pnpm build

# Expose the port the app runs on
EXPOSE ${NEXT_JS_PORT}

# Start the application using PM2
CMD ["pm2-runtime", "start", "npm", "--", "start"]