# Use the official Node.js image as the base image
FROM node:latest

# Set the working directory
WORKDIR /apps/frontend

# Copy package.json and package-lock.json
COPY package*.json ./

# # Install dependencies
# RUN npm install

# # Install PM2 globally
# RUN npm install -g pm2

# Copy the rest of the application code
COPY . .

# Build the application
RUN pnpm build

# Expose the port the app runs on
EXPOSE ${NEXT_JS_PORT}

# Start the application using PM2
CMD ["pm2-runtime", "start", "npm", "--", "start"]