services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
      target: "nest_backend_runner"
    container_name: backend
    ports:
      - "8081:8081"
    volumes:
      - ./apps/backend-app/dist:/app/backend-app/dist:ro
      - ./node_modules:/app/node_modules:ro
      - .env:/app/.env:ro
    restart: unless-stopped
    networks:
      - hyperhire
  frontend:
    build:
      context: .
      dockerfile: dockerfile
      target: "next_frontend_runner"
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./node_modules:/app/node_modules:ro
      - ./apps/frontend-app/.next/standalone:/app/frontend-app
      - ./apps/frontend-app/.next/static:/app/frontend-app/.next/static
      - ./apps/frontend-app/public:/app/frontend-app/public
      - .env:/app/.env:ro
    restart: unless-stopped
    networks:
      - hyperhire

networks:
  hyperhire:
    driver: bridge
