services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
      target: "nest_backend_runner"
    container_name: backend
    ports:
      - "8081:8081"
    volumes:
      - ./apps/backend-app/dist:/app/backend-app/dist:ro
      - ./node_modules:/app/node_modules:ro
      - .env:/app/.env:ro
    restart: unless-stopped
