# Use the official Node.js image as the base image
FROM node:latest

# Set the working directory
WORKDIR /apps/backend

# Copy package.json and package-lock.json
COPY package*.json ./

# Set environment to production
ENV NODE_ENV=production

# # Install PM2 globally and production dependencies
# RUN npm install -g pm2 && npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE ${NEST_APP_PORT}

# Command to run the application using PM2
CMD ["pm2-runtime", "start", "ecosystem.config.js", "--env", "production"]