# Use the official Node.js image as the base image
FROM node:latest

# Set the working directory
WORKDIR /app/apps/backend-app

# Copy package.json and package-lock.json
COPY package*.json ./

# Set environment to production
ENV NODE_ENV=production

# Copy the rest of the application code
COPY ./apps/backend-app .

# Build the application
RUN pnpm build

# Expose the port the app runs on
EXPOSE ${NEST_APP_PORT}

# Command to run the application using PM2
CMD ["pm2-runtime", "start", "ecosystem.config.js", "--env", "production"]