name: Nx CI/CD (pnpm)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures proper commit history for Nx caching

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8  # Use the latest stable PNPM version
          run_install: false  # Prevent automatic install

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: List All Artifacts Before Cleanup
        run: find . -type d -name "artifacts"

      - name: Cleanup Old Artifacts
        run: |
          if [ -d "artifacts" ]; then
            echo "Removing existing artifacts..."
            rm -rf artifacts
          fi
          mkdir -p artifacts/app --output-path=artifacts/app/backend
      
      - name: Build backend
        run: pnpm exec nx build backend-app --parallel --skip-nx-cache
        
      - name: Move Backend Build Output
        run: mkdir -p artifacts/apps/backend-app && mv dist/apps/backend-app/* artifacts/apps/backend-app

      - name: Build Next.js App (SSR)
        run: pnpm exec nx build frontend-app --parallel --skip-nx-cache
      
      - name: Move Frontend Build Output
        run: mkdir -p artifacts/apps/frontend-app && mv apps/frontend-app/.next artifacts/apps/frontend-app

      - name: Commit Built Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "ci: auto-commit built files [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }} || echo "No changes to push"
