name: Nx CI/CD (pnpm)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures proper commit history for Nx caching

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm exec prisma generate

      - name: Cleanup Artifacts
        run: find . -type d -name "artifacts" -exec rm -rf {} + || true

      - name: Build Nest.js App (Backend)
        run: pnpm exec nx build backend-app --parallel --skip-nx-cache

      - name: Build Next.js App (SSR)
        run: pnpm exec nx build frontend-app --parallel --skip-nx-cache
      
      - name: Move Prisma Client to Backend Artifact
        run: |
          mkdir -p $GITHUB_WORKSPACE/artifacts/apps/backend-app/node_modules
          mv -v node_modules/prisma $GITHUB_WORKSPACE/artifacts/apps/backend-app/node_modules/
          mv -v node_modules/@prisma $GITHUB_WORKSPACE/artifacts/apps/backend-app/node_modules/

      - name: Move Backend Build Output
        run: |
          mkdir -p $GITHUB_WORKSPACE/artifacts/apps/backend-app
          mv -v $GITHUB_WORKSPACE/apps/backend-app/dist $GITHUB_WORKSPACE/artifacts/apps/backend-app
      
      - name: Move Frontend Build Output
        run: |
          mkdir -p $GITHUB_WORKSPACE/artifacts/apps/frontend-app
          mv -v $GITHUB_WORKSPACE/apps/frontend-app/.next $GITHUB_WORKSPACE/artifacts/apps/frontend-app
      
      
      - name: Check if Artifacts Are Ignored
        run: git check-ignore -v artifacts/* || echo "Artifacts are NOT ignored"

      - name: List Generated Artifacts
        run: ls -R artifacts || echo "Artifacts folder is empty!"

      - name: Show Git Status Before Commit
        run: git status --short

      - name: Commit Built Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          
          # Ensure artifacts are not ignored
          git add -f artifacts/
          
          # Only commit if there are actual changes
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci: auto-commit built files [skip ci]"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
          fi
