name: Nx CI/CD (pnpm)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Pastikan history untuk Nx caching

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Cleanup Artifacts
        run: rm -rf artifacts || true

      # 🔹 Install Prisma Client sebelum build
      - name: Install Prisma Client
        run: pnpm add @prisma/client --filter backend-app

      # 🔹 Generate Prisma Client agar bisa digunakan dalam build
      - name: Generate Prisma Client
        run: pnpm exec prisma generate --schema=prisma/schema.prisma

      # 🔹 Build Backend (Nest.js)
      - name: Build Nest.js App (Backend)
        run: pnpm exec nx build backend-app --parallel --skip-nx-cache

      # 🔹 Build Frontend (Next.js)
      - name: Build Next.js App (Frontend)
        run: pnpm exec nx build frontend-app --parallel --skip-nx-cache

      # 🔹 Simpan hasil build backend
      - name: Move Backend Build Output
        run: |
          mkdir -p artifacts/apps/backend-app
          mv -v apps/backend-app/dist artifacts/apps/backend-app
          cp -R prisma artifacts/apps/backend-app/prisma

      # 🔹 Install dependencies production di dalam artifacts (supaya Prisma Client tetap ada)
      - name: Install Production Dependencies in Artifacts
        run: |
          cd artifacts/apps/backend-app
          pnpm install --prod

      # 🔹 Copy Prisma Client supaya tetap bisa diakses
      - name: Ensure Prisma Client Exists in Artifact
        run: |
          mkdir -p artifacts/apps/backend-app/node_modules
          cp -R node_modules/.pnpm artifacts/apps/backend-app/
          cp -R node_modules/@prisma artifacts/apps/backend-app/node_modules/
          cp -R node_modules/prisma artifacts/apps/backend-app/node_modules/

      # 🔹 Pastikan Prisma Client benar-benar ada di artifacts
      - name: Verify Prisma Client
        run: ls -R artifacts/apps/backend-app/node_modules/@prisma || echo "Prisma Client missing!"

      # 🔹 Simpan hasil build frontend
      - name: Move Frontend Build Output
        run: |
          mkdir -p artifacts/apps/frontend-app
          mv -v apps/frontend-app/.next artifacts/apps/frontend-app

      # 🔹 Upload hasil build backend (backend siap deploy)
      - name: Upload Backend Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: artifacts/apps/backend-app

      # 🔹 Upload hasil build frontend (frontend siap deploy)
      - name: Upload Frontend Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: artifacts/apps/frontend-app

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 🔹 Download backend artifact untuk deploy
      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-build
          path: artifacts/apps/backend-app

      # 🔹 Download frontend artifact untuk deploy
      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: artifacts/apps/frontend-app

      # 🔹 Pastikan Prisma Client masih ada setelah download
      - name: Verify Prisma Client After Download
        run: ls -R artifacts/apps/backend-app/node_modules/@prisma || echo "Prisma Client missing!"

      # 🔹 Deploy Backend (contoh: Docker atau SSH)
      - name: Deploy Backend
        run: echo "Deploying backend..."

      # 🔹 Deploy Frontend (contoh: Vercel atau S3)
      - name: Deploy Frontend
        run: echo "Deploying frontend..."
