name: Nx CI/CD (pnpm)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures proper commit history for Nx caching

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8  # Use the latest stable PNPM version
          run_install: false  # Prevent automatic install

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile
      
      - name: Build Affected Projects with Custom Output
        run: |
          AFFECTED_PROJECTS=$(pnpm nx affected --target=build --base=origin/main --plain)
      
          if [ -z "$AFFECTED_PROJECTS" ]; then
            echo "No affected projects to build."
            exit 0
          fi
      
          for project in $AFFECTED_PROJECTS; do
            echo "Building $project..."
            pnpm nx build $project --outputPath=deployment-artifacts/$project
          done

      - name: Commit Built Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "ci: auto-commit built files [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }} || echo "No changes to push"
